/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.siłownia;

/**
 *
 * @author Damian
 */
public class OkienkoGlowne extends javax.swing.JFrame {

    /**
     * Creates new form OkienkoGlowne
     */
    public OkienkoGlowne() {
        initComponents();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_StworzPlanTrenigowy = new javax.swing.JFrame();
        jPanel_PartieCiala = new javax.swing.JPanel();
        jButton_Barki = new javax.swing.JButton();
        jButton_Klata = new javax.swing.JButton();
        jButton_Plecy = new javax.swing.JButton();
        jButton_Biceps = new javax.swing.JButton();
        jButton_Brzuch = new javax.swing.JButton();
        jButton_Triceps = new javax.swing.JButton();
        jButton_Nogi = new javax.swing.JButton();
        jButton_Rozgrzewka = new javax.swing.JButton();
        jButton_Kondycyjne = new javax.swing.JButton();
        jButton_Inne = new javax.swing.JButton();
        jPanel_GrafikaSilacz = new javax.swing.JPanel();
        jLabel_Tytul = new javax.swing.JLabel();
        jButton_Powrot = new javax.swing.JButton();
        jFrame_EfektyTreningowe = new javax.swing.JFrame();
        jPanel_WymiaryCiała = new javax.swing.JPanel();
        jLabel_Tytuł = new javax.swing.JLabel();
        jTextField_WymiarLydki = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_WymiarUdo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_WymiarBiodro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_WymiarTalia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_WymiarKlata = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_WymiarKark = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_WymiarBiceps = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_WymiarPrzedramie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_WymiarWaga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_WymiarPas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel_GrafikaMiara = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_TytulAplikacji = new javax.swing.JLabel();
        jButton_S = new javax.swing.JButton();
        jButton_E = new javax.swing.JButton();

        JPanel_Gafika GrafikaSilacza = new JPanel_Gafika("silacz.jpg");
        jPanel_GrafikaSilacz=GrafikaSilacza;
        jFrame_StworzPlanTrenigowy.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame_StworzPlanTrenigowy.setTitle("Silka");
        jFrame_StworzPlanTrenigowy.setLocationRelativeTo(null);
        pack();

        jPanel_PartieCiala.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 255), new java.awt.Color(51, 51, 255)));

        jButton_Barki.setText("Barki");

        jButton_Klata.setText("Klatka");

        jButton_Plecy.setText("Plecy");

        jButton_Biceps.setText("Biceps");

        jButton_Brzuch.setText("Brzuch");

        jButton_Triceps.setText("Triceps");

        jButton_Nogi.setText("Nogi");
        jButton_Nogi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NogiActionPerformed(evt);
            }
        });

        jButton_Rozgrzewka.setText("Rozgrzewka");

        jButton_Kondycyjne.setText("Kondycyjne");

        jButton_Inne.setText("Inne");

        javax.swing.GroupLayout jPanel_PartieCialaLayout = new javax.swing.GroupLayout(jPanel_PartieCiala);
        jPanel_PartieCiala.setLayout(jPanel_PartieCialaLayout);
        jPanel_PartieCialaLayout.setHorizontalGroup(
            jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PartieCialaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Brzuch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Plecy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Rozgrzewka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Nogi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Barki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PartieCialaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Kondycyjne))
                    .addComponent(jButton_Klata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Biceps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Triceps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Inne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel_PartieCialaLayout.setVerticalGroup(
            jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PartieCialaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Rozgrzewka)
                    .addComponent(jButton_Kondycyjne))
                .addGap(18, 18, 18)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Plecy)
                    .addComponent(jButton_Klata))
                .addGap(18, 18, 18)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Biceps)
                    .addComponent(jButton_Brzuch))
                .addGap(18, 18, 18)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Triceps)
                    .addComponent(jButton_Nogi))
                .addGap(18, 18, 18)
                .addGroup(jPanel_PartieCialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Barki)
                    .addComponent(jButton_Inne))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel_GrafikaSilacz.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), new java.awt.Color(0, 204, 204)));
        jPanel_GrafikaSilacz.setPreferredSize(new java.awt.Dimension(100, 55));

        javax.swing.GroupLayout jPanel_GrafikaSilaczLayout = new javax.swing.GroupLayout(jPanel_GrafikaSilacz);
        jPanel_GrafikaSilacz.setLayout(jPanel_GrafikaSilaczLayout);
        jPanel_GrafikaSilaczLayout.setHorizontalGroup(
            jPanel_GrafikaSilaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel_GrafikaSilaczLayout.setVerticalGroup(
            jPanel_GrafikaSilaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel_Tytul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Tytul.setText("Partie Ciała ");

        jButton_Powrot.setText("Powrót ");
        jButton_Powrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PowrotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame_StworzPlanTrenigowyLayout = new javax.swing.GroupLayout(jFrame_StworzPlanTrenigowy.getContentPane());
        jFrame_StworzPlanTrenigowy.getContentPane().setLayout(jFrame_StworzPlanTrenigowyLayout);
        jFrame_StworzPlanTrenigowyLayout.setHorizontalGroup(
            jFrame_StworzPlanTrenigowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_StworzPlanTrenigowyLayout.createSequentialGroup()
                .addGroup(jFrame_StworzPlanTrenigowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFrame_StworzPlanTrenigowyLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel_Tytul))
                    .addGroup(jFrame_StworzPlanTrenigowyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_StworzPlanTrenigowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Powrot)
                            .addComponent(jPanel_PartieCiala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel_GrafikaSilacz, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jFrame_StworzPlanTrenigowyLayout.setVerticalGroup(
            jFrame_StworzPlanTrenigowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_StworzPlanTrenigowyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Tytul)
                .addGap(15, 15, 15)
                .addGroup(jFrame_StworzPlanTrenigowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_GrafikaSilacz, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jPanel_PartieCiala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Powrot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame_EfektyTreningowe.setTitle("Silka");
        JPanel_Gafika GrafikaMiara = new JPanel_Gafika("miara.jpg");
        jPanel_GrafikaMiara=GrafikaMiara;
        jFrame_EfektyTreningowe.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFrame_StworzPlanTrenigowy.setLocationRelativeTo(null);
        pack();

        jPanel_WymiaryCiała.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 0), null));

        jLabel_Tytuł.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel_Tytuł.setText("Wymiary ");

        jLabel3.setText("Łydka");

        jLabel4.setText("Udo");

        jLabel2.setText("Biodra");

        jLabel6.setText("Talia");

        jLabel7.setText("Klatka");

        jLabel5.setText("Kark");

        jLabel8.setText("Biceps");

        jLabel9.setText("Przedramie");

        jLabel10.setText("Waga");

        jLabel11.setText("Pas");

        javax.swing.GroupLayout jPanel_WymiaryCiałaLayout = new javax.swing.GroupLayout(jPanel_WymiaryCiała);
        jPanel_WymiaryCiała.setLayout(jPanel_WymiaryCiałaLayout);
        jPanel_WymiaryCiałaLayout.setHorizontalGroup(
            jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                        .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_WymiarBiodro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_WymiarLydki, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                        .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_WymiarWaga)
                            .addComponent(jTextField_WymiarBiceps)
                            .addComponent(jTextField_WymiarKlata, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_WymiarPrzedramie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_WymiaryCiałaLayout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_WymiarKark, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                                            .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_WymiarUdo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_WymiarTalia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_WymiarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_WymiaryCiałaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Tytuł)
                .addGap(69, 69, 69))
        );
        jPanel_WymiaryCiałaLayout.setVerticalGroup(
            jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WymiaryCiałaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Tytuł)
                .addGap(18, 18, 18)
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_WymiarLydki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_WymiarUdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_WymiarBiodro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_WymiarTalia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_WymiarKlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_WymiarKark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_WymiarBiceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_WymiarPrzedramie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_WymiaryCiałaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_WymiarWaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_WymiarPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_GrafikaMiara.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 204, 0)));

        javax.swing.GroupLayout jPanel_GrafikaMiaraLayout = new javax.swing.GroupLayout(jPanel_GrafikaMiara);
        jPanel_GrafikaMiara.setLayout(jPanel_GrafikaMiaraLayout);
        jPanel_GrafikaMiaraLayout.setHorizontalGroup(
            jPanel_GrafikaMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jPanel_GrafikaMiaraLayout.setVerticalGroup(
            jPanel_GrafikaMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Efekty Treningowe ");

        javax.swing.GroupLayout jFrame_EfektyTreningoweLayout = new javax.swing.GroupLayout(jFrame_EfektyTreningowe.getContentPane());
        jFrame_EfektyTreningowe.getContentPane().setLayout(jFrame_EfektyTreningoweLayout);
        jFrame_EfektyTreningoweLayout.setHorizontalGroup(
            jFrame_EfektyTreningoweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_EfektyTreningoweLayout.createSequentialGroup()
                .addGroup(jFrame_EfektyTreningoweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_EfektyTreningoweLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_WymiaryCiała, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel_GrafikaMiara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_EfektyTreningoweLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jFrame_EfektyTreningoweLayout.setVerticalGroup(
            jFrame_EfektyTreningoweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_EfektyTreningoweLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame_EfektyTreningoweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_WymiaryCiała, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_GrafikaMiara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silka");

        jLabel_TytulAplikacji.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_TytulAplikacji.setText("Analizator Treningu ");

        jButton_S.setText("Stwórz plan treningowy");
        jButton_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SActionPerformed(evt);
            }
        });

        jButton_E.setText("Efekty treningowe ");
        jButton_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel_TytulAplikacji, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton_S))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton_E)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_TytulAplikacji)
                .addGap(29, 29, 29)
                .addComponent(jButton_S)
                .addGap(28, 28, 28)
                .addComponent(jButton_E)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame_StworzPlanTrenigowy.setVisible(true);
        jFrame_StworzPlanTrenigowy.pack();
        
    }//GEN-LAST:event_jButton_SActionPerformed

    private void jButton_NogiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NogiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_NogiActionPerformed

    private void jButton_PowrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PowrotActionPerformed
      
        jFrame_StworzPlanTrenigowy.setVisible(false);
        this.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton_PowrotActionPerformed

    private void jButton_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EActionPerformed
       
       
        this.setVisible(false);
         jFrame_EfektyTreningowe.setVisible(true);
        
        
    }//GEN-LAST:event_jButton_EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkienkoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkienkoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkienkoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkienkoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkienkoGlowne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Barki;
    private javax.swing.JButton jButton_Biceps;
    private javax.swing.JButton jButton_Brzuch;
    private javax.swing.JButton jButton_E;
    private javax.swing.JButton jButton_Inne;
    private javax.swing.JButton jButton_Klata;
    private javax.swing.JButton jButton_Kondycyjne;
    private javax.swing.JButton jButton_Nogi;
    private javax.swing.JButton jButton_Plecy;
    private javax.swing.JButton jButton_Powrot;
    private javax.swing.JButton jButton_Rozgrzewka;
    private javax.swing.JButton jButton_S;
    private javax.swing.JButton jButton_Triceps;
    private javax.swing.JFrame jFrame_EfektyTreningowe;
    private javax.swing.JFrame jFrame_StworzPlanTrenigowy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Tytul;
    private javax.swing.JLabel jLabel_TytulAplikacji;
    private javax.swing.JLabel jLabel_Tytuł;
    private javax.swing.JPanel jPanel_GrafikaMiara;
    private javax.swing.JPanel jPanel_GrafikaSilacz;
    private javax.swing.JPanel jPanel_PartieCiala;
    private javax.swing.JPanel jPanel_WymiaryCiała;
    private javax.swing.JTextField jTextField_WymiarBiceps;
    private javax.swing.JTextField jTextField_WymiarBiodro;
    private javax.swing.JTextField jTextField_WymiarKark;
    private javax.swing.JTextField jTextField_WymiarKlata;
    private javax.swing.JTextField jTextField_WymiarLydki;
    private javax.swing.JTextField jTextField_WymiarPas;
    private javax.swing.JTextField jTextField_WymiarPrzedramie;
    private javax.swing.JTextField jTextField_WymiarTalia;
    private javax.swing.JTextField jTextField_WymiarUdo;
    private javax.swing.JTextField jTextField_WymiarWaga;
    // End of variables declaration//GEN-END:variables
}
